[package]
name = "diag"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
common = { path = "../common" }
locale = { path = "../i18n" }
annotate-snippets = "0.12.10"
anstream = "0.6.21"
