[package]
name = "syntax"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
common = { path = "../common" }
token = { path = "../token" }
macros = { path = "../macros" }
num-bigint = "0.4.6"
